version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
    groups:
      async-ecosystem:
        patterns:
          - "tokio*"
          - "hyper*"
          - "tower*"
          - "futures*"
      protobuf-ecosystem:
        patterns:
          - "prost*"
          - "tonic*"
      serialization:
        patterns:
          - "serde*"
      tracing-ecosystem:
        patterns:
          - "tracing*"
      rustls-ecosystem:
        patterns:
          - "rustls*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "ci"
